apiVersion: v1
kind: Service
metadata:
  name: cataloguenpservice-srv
spec:
  type: NodePort
  selector:
    app: catalogueservice
  ports:
    - name: catalogueservice
      protocol: TCP
      port: 80
      targetPort: 80