apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmvc
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      containers:
        - name: webmvc
          image: darren8790/webmvc:latest
---
apiVersion: v1
kind: Service
metadata:
  name: webmvc-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: webmvc
  ports:
  - name: webmvc
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webmvc-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: webmvc
  ports:
  - protocol: TCP
    port: 2500
    targetPort: 2500